apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubia
spec:
  rules:
    - host: kubia.example.com
      http:
        paths:
          - path: /kubia
            pathType: Prefix
            backend:
              service:
                name: kubia-nodeport
                port:
                  number: 80
          - path: /bar
            pathType: Prefix
            backend:
              service:
                name: bar
                port:
                  number: 80
